// No need for "use client" here since metadata is for server-side
import "./globals.css";
import NavigationBar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import { LoaderProvider } from "@/app/context/LoaderContext";
import GlobalBackground from "./components/GlobalBackground/background";

export const metadata = {
  title: "BPO Brigade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        

        <LoaderProvider>
          <GlobalBackground /> {/* Background stays behind everything */}
          <div className="relative z-10">
            <NavigationBar />
            {children}
            <Footer className="z-50" />
          </div>
        </LoaderProvider>
      </body>
    </html>
  );
}
